name: Browser Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  dusk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, bcmath, gd, curl, sqlite3
        coverage: none

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Copy .env file and configure for Dusk
      run: |
        cp .env.example .env
        echo "APP_ENV=testing" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_URL=http://127.0.0.1:8000" >> .env
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=database/dusk.sqlite" >> .env
        echo "CACHE_DRIVER=array" >> .env
        echo "SESSION_DRIVER=array" >> .env
        echo "QUEUE_CONNECTION=sync" >> .env
        echo "LOG_CHANNEL=stderr" >> .env

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate application key
      run: php artisan key:generate --force

    - name: Create SQLite database for Dusk
      run: |
        mkdir -p database
        touch database/dusk.sqlite

    - name: Install npm dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        fi

    - name: Install ChromeDriver
      run: php artisan dusk:chrome-driver --detect

    - name: Start ChromeDriver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

    - name: Run Laravel server
      run: php artisan serve --no-reload > /dev/null 2>&1 &

    - name: Run Dusk tests
      env:
        APP_URL: http://127.0.0.1:8000
        DB_CONNECTION: sqlite
        DB_DATABASE: database/dusk.sqlite
        APP_ENV: testing
      run: php artisan dusk --without-tty