name: Validate Composer Files

on:
  push:
    paths:
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    paths:
      - 'composer.json'
      - 'composer.lock'

jobs:
  composer-validate:
    name: Validate composer.json & composer.lock
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --no-check-all --no-check-publish --check-lock
